spring.application.name=NotificationService
server.port=9898

eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saieshpatil521@gmail.com
spring.mail.password=kckufzzkjxluokjc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000